---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  client_rb:
    chef_license: accept

verifier:
  name: inspec

platforms:
  - name: opscode-ubuntu-18.04-chef-14
    driver:
      box: bento/ubuntu-18.04
    provisioner:
      product_name: chef
      product_version: latest

suites:
  - name: producer
    run_list:
      - recipe[barito-flow::producer]
      - recipe[consul::default]
      - recipe[barito-flow::producer_consul_register]
    driver_config:
      customize:
        memory: 2048
      network:
        - ["private_network", { ip: "192.168.33.26" }]
    verifier:
      inspec_tests:
        - test/integration/producer
    attributes:
      consul:
        run_as_server: false
        hosts: ["127.0.0.1"]
        cli_opts:
          advertise: "192.168.33.26"
  - name: consumer
    run_list:
      - recipe[barito-flow::consumer]
    driver_config:
      customize:
        memory: 2048
      network:
        - ["private_network", { ip: "192.168.33.25" }]
    verifier:
      inspec_tests:
        - test/integration/consumer
    attributes:
  - name: router
    run_list:
      - recipe[barito-flow::router]
    verifier:
      inspec_tests:
        - test/integration/router
    attributes:
      barito-flow:
        router:
          env_vars:
            BARITO_ROUTER_ADDRESS: ":8081"
            BARITO_KIBANA_ROUTER_ADDRESS: ":8082"
            BARITO_XTAIL_ROUTER_ADDRESS: ":8083"
            BARITO_ROUTER_MARKET_URL: "http://localhost:8080/api/apps"
